### PR TITLE
Bug Fix: Bookmarks for unregistered users

### LINKED ISSUE #35: Make Bookmark display message if user is not logged in
`GET /tutorials/:id`

Currently the Bookmark link will redirect to the login page and stop the video from playing which leads to a rather jarring experience.

Let's display a message that says "User must login to bookmark videos." A tooltip or flash notice could be good options?

### PR DESCRIPTION
**Pull request by alerrian**
* Fixed bug that allowed unregistered users to create bookmarks
* Added `before_action` check to controller
* Fixed tutorial show page to reflect changes to logic change due to lack of user id on button.

### CODE REVIEW

File: app/controllers/user_videos_controller.rb [hunk 1]
```diff
@@ -18,4 +22,11 @@ def create
   def user_video_params
     params.permit(:user_id, :video_id)
   end
+
+  def verify_user
+    if current_user.nil?
+      flash[:notice] = 'User must login to bookmark videos.'
+      redirect_back(fallback_location: root_path)
```
Comment (nkeller1) [inline app/controllers/user_videos_controller.rb]: like this redirect!

File: spec/features/user/user_can_bookmark_a_video_spec.rb [hunk 2]
```diff
@@ -27,8 +27,19 @@
...
 
     click_on 'Bookmark'
-    expect(page).to have_content("Bookmark added to your dashboard")
+    expect(page).to have_content('Bookmark added to your dashboard')
     click_on 'Bookmark'
-    expect(page).to have_content("Already in your bookmarks")
+    expect(page).to have_content('Already in your bookmarks')
+  end
+
+  it 'cannot add bookmark if unregistered' do
```
Comment (nkeller1) [inline spec/features/user/user_can_bookmark_a_video_spec.rb:35]: good sad path test here

**Review by nkeller1 — APPROVED** [review]
